minio:
  endpoint: minio:9000
  access_key: MINIO_ACCESS_KEY
  secret_key: MINIO_SECRET_KEY
  bucket: traffic-snapshots
collector:
  cameras_api: "https://api.notis.vn/v4/cameras/bybbox?lat1=11.160767&lng1=106.554166&lat2=9.45&lng2=128.99999"
  interval: 60
